[settings]
# Конфигурация для тестирования этапа 2 (тестовый репозиторий)
package_name = A
repository_url = tests/stage2_test_repo.json
test_mode = true
package_version = focal
ascii_tree = true
max_depth = 3
filter_substring =
