[settings]
# Конфигурация для тестирования этапа 2 (реальный репозиторий)
package_name = curl
repository_url = http://archive.ubuntu.com/ubuntu
test_mode = false
package_version = focal
ascii_tree = true
max_depth = 2
filter_substring =
