[settings]
# Пример 2: Анализ пакета python3

package_name = python3
repository_url = http://archive.ubuntu.com/ubuntu
test_mode = false
package_version = focal
max_depth = 2
filter_substring =
plantuml_output = visualizations/graph_python3.puml
show_ascii_tree = true
