[settings]
# Пример 3: Анализ пакета nginx

package_name = nginx
repository_url = http://archive.ubuntu.com/ubuntu
test_mode = false
package_version = focal
max_depth = 2
filter_substring =
plantuml_output = visualizations/graph_nginx.puml
show_ascii_tree = true
