@startuml

"curl" --> "libc6"
"curl" --> "libcurl4"
"curl" --> "zlib1g"
"libbrotli1" --> "libc6"
"libc6" --> "libgcc-s1"
"libc6" --> "libcrypt1"
"libcrypt1" --> "libc6"
"libcurl4" --> "libbrotli1"
"libcurl4" --> "libc6"
"libcurl4" --> "libgssapi-krb5-2"
"libcurl4" --> "libidn2-0"
"libcurl4" --> "libldap-2.4-2"
"libcurl4" --> "libnghttp2-14"
"libcurl4" --> "libpsl5"
"libcurl4" --> "librtmp1"
"libcurl4" --> "libssh-4"
"libcurl4" --> "libssl1.1"
"libcurl4" --> "zlib1g"
"libgcc-s1" --> "gcc-10-base"
"libgcc-s1" --> "libc6"
"libgssapi-krb5-2" --> "libc6"
"libgssapi-krb5-2" --> "libcom-err2"
"libgssapi-krb5-2" --> "libk5crypto3"
"libgssapi-krb5-2" --> "libkrb5-3"
"libgssapi-krb5-2" --> "libkrb5support0"
"libidn2-0" --> "libc6"
"libidn2-0" --> "libunistring2"
"libldap-2.4-2" --> "libc6"
"libldap-2.4-2" --> "libgnutls30"
"libldap-2.4-2" --> "libgssapi3-heimdal"
"libldap-2.4-2" --> "libsasl2-2"
"libldap-2.4-2" --> "libldap-common"
"libnghttp2-14" --> "libc6"
"libpsl5" --> "libidn2-0"
"libpsl5" --> "libc6"
"libpsl5" --> "libunistring2"
"librtmp1" --> "libc6"
"librtmp1" --> "libgmp10"
"librtmp1" --> "libgnutls30"
"librtmp1" --> "libhogweed5"
"librtmp1" --> "libnettle7"
"librtmp1" --> "zlib1g"
"libssh-4" --> "libc6"
"libssh-4" --> "libgssapi-krb5-2"
"libssh-4" --> "libssl1.1"
"libssh-4" --> "zlib1g"
"libssl1.1" --> "libc6"
"libssl1.1" --> "debconf"
"zlib1g" --> "libc6"

@enduml