@startuml

"git" --> "libc6"
"git" --> "libcurl3-gnutls"
"git" --> "libexpat1"
"git" --> "libpcre2-8-0"
"git" --> "zlib1g"
"git" --> "perl"
"git" --> "liberror-perl"
"git" --> "git-man"
"git" --> "git-man"
"libbrotli1" --> "libc6"
"libc6" --> "libgcc-s1"
"libc6" --> "libcrypt1"
"libcrypt1" --> "libc6"
"libcurl3-gnutls" --> "libbrotli1"
"libcurl3-gnutls" --> "libc6"
"libcurl3-gnutls" --> "libgnutls30"
"libcurl3-gnutls" --> "libgssapi-krb5-2"
"libcurl3-gnutls" --> "libidn2-0"
"libcurl3-gnutls" --> "libldap-2.4-2"
"libcurl3-gnutls" --> "libnettle7"
"libcurl3-gnutls" --> "libnghttp2-14"
"libcurl3-gnutls" --> "libpsl5"
"libcurl3-gnutls" --> "librtmp1"
"libcurl3-gnutls" --> "libssh-4"
"libcurl3-gnutls" --> "zlib1g"
"liberror-perl" --> "perl:any"
"libexpat1" --> "libc6"
"libgcc-s1" --> "gcc-10-base"
"libgcc-s1" --> "libc6"
"libgnutls30" --> "libgmp10"
"libgnutls30" --> "libc6"
"libgnutls30" --> "libhogweed5"
"libgnutls30" --> "libidn2-0"
"libgnutls30" --> "libnettle7"
"libgnutls30" --> "libp11-kit0"
"libgnutls30" --> "libtasn1-6"
"libgnutls30" --> "libunistring2"
"libgssapi-krb5-2" --> "libc6"
"libgssapi-krb5-2" --> "libcom-err2"
"libgssapi-krb5-2" --> "libk5crypto3"
"libgssapi-krb5-2" --> "libkrb5-3"
"libgssapi-krb5-2" --> "libkrb5support0"
"libidn2-0" --> "libc6"
"libidn2-0" --> "libunistring2"
"libldap-2.4-2" --> "libc6"
"libldap-2.4-2" --> "libgnutls30"
"libldap-2.4-2" --> "libgssapi3-heimdal"
"libldap-2.4-2" --> "libsasl2-2"
"libldap-2.4-2" --> "libldap-common"
"libnettle7" --> "libc6"
"libnghttp2-14" --> "libc6"
"libpcre2-8-0" --> "libc6"
"libperl5.30" --> "libbz2-1.0"
"libperl5.30" --> "libc6"
"libperl5.30" --> "libcrypt1"
"libperl5.30" --> "libdb5.3"
"libperl5.30" --> "libgdbm-compat4"
"libperl5.30" --> "libgdbm6"
"libperl5.30" --> "zlib1g"
"libperl5.30" --> "perl-modules-5.30"
"libpsl5" --> "libidn2-0"
"libpsl5" --> "libc6"
"libpsl5" --> "libunistring2"
"librtmp1" --> "libc6"
"librtmp1" --> "libgmp10"
"librtmp1" --> "libgnutls30"
"librtmp1" --> "libhogweed5"
"librtmp1" --> "libnettle7"
"librtmp1" --> "zlib1g"
"libssh-4" --> "libc6"
"libssh-4" --> "libgssapi-krb5-2"
"libssh-4" --> "libssl1.1"
"libssh-4" --> "zlib1g"
"perl" --> "perl-base"
"perl" --> "perl-modules-5.30"
"perl" --> "libperl5.30"
"perl-modules-5.30" --> "perl-base"
"zlib1g" --> "libc6"

@enduml